// noinspection SpellCheckingInspection

export const CATEGORY_ICONS = [
    { name: "WindowsXPFavorite", label: "Star" },
    { name: "WindowsXPmmcndmgr4", label: "Clock" },
    { name: "WindowsXPHearts", label: "Heart" },
    { name: "WindowsXPmmcndmgr21", label: "Flag" },
    { name: "WindowsXPmmcndmgr17", label: "Book" },
    { name: "WindowsXPPhone", label: "Phone" },
    { name: "WindowsXPAudioCD", label: "Music" },
    { name: "AVGSGnintendoDS", label: "Gaming" },
    { name: "WindowsXPmmcndmgr29", label: "Cube" },
    { name: "WindowsXPActivation", label: "Keys" },
    { name: "WindowsXPPaint", label: "Paint" },
    { name: "WindowsXPShell329", label: "Pie chart" },
    { name: "WindowsXPMyComputer2", label: "Computer" },
    { name: "WordpadXP", label: "Notepad" },
    { name: "RegionalAndLanguageOptions", label: "Planet" },
    { name: "MysteryThemeRecycleBin", label: "Miscellaneous" },
    { name: "WindowsXPMail", label: "Mail" },
    { name: "WindowsXPCamera", label: "Camera" },
    { name: "Icons2257", label: "Cat" },
    { name: "AcDSee", label: "Eye" },
    { name: "AquariumTheme", label: "Treasure" },
    { name: "BigMoneyDeluxe", label: "Money bag" },
    { name: "Minesweeper2", label: "Smiley face" },
    { name: "SevenSeas", label: "Pirate" },
    { name: "StrictlyPaperoll", label: "Toilet paper" },
    { name: "Steam2011", label: "Steam" },
    { name: "Windows31Progman", label: "Cassette" },
    { name: "WindowsVistaLiveMessenger", label: "Social" },
    { name: "PepsiThemeMyComputer", label: "Soda can" },
    { name: "VisualStudioCARS", label: "Cars" },
    { name: "Bejeweled", label: "Diamond" },
    { name: "FashionTheme2", label: "Lipstick" },
    { name: "FashionTheme", label: "Purse" },
    { name: "IntelliPoint", label: "Gentleman" },
    { name: "LeonardoDaVinci", label: "Writing book" },
    { name: "NatureTheme1", label: "Bonfire" },
    { name: "NetscapeHome", label: "House" },
    { name: "PhotoDiscRecycleBin", label: "Suitcase" },
    { name: "RNRNetworkNeighborhood", label: "Drums" },
    { name: "RollerCoasterTycoon", label: "Panda" },
    { name: "VisualStudioPlane", label: "Airplane" },
    { name: "WindowsPifmgr8", label: "Football" },
    { name: "Windows95SavedSearch", label: "Paper" },
    { name: "Windows95Pifmgr13", label: "Domino" }

];

// noinspection JSUnusedGlobalSymbols
export const NO_CATEGORY = { name: null, label: "Uncategorized", icon: "Windows31ProgmanIcon" };